USE DATABASE DB_SALES_DEV;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW.ORDERS (
  ORDER_ID NUMBER NOT NULL,
  CUSTOMER_ID NUMBER NOT NULL,
  ORDER_TS TIMESTAMP_NTZ NOT NULL,
  AMOUNT NUMBER(18, 2) NOT NULL
);

USE SCHEMA SILVER;

CREATE OR REPLACE VIEW SILVER.ORDERS_VALIDATED AS
SELECT ORDER_ID, CUSTOMER_ID, ORDER_TS, AMOUNT
FROM RAW.ORDERS
WHERE AMOUNT >= 0;

USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.DAILY_REVENUE AS
SELECT TO_DATE(ORDER_TS) AS ORDER_DATE, SUM(AMOUNT) AS REVENUE
FROM SILVER.ORDERS_VALIDATED
GROUP BY ORDER_DATE;
