output "resource_group_name" {
  value       = azurerm_resource_group.state.name
  description = "Resource group for remote Terraform state"
}

output "storage_account_name" {
  value       = azurerm_storage_account.state.name
  description = "Storage account for remote Terraform state"
}

output "container_name" {
  value       = azurerm_storage_container.state.name
  description = "Storage container for remote Terraform state"
}

output "storage_account_id" {
  value       = azurerm_storage_account.state.id
  description = "Resource ID of the storage account (for RBAC assignments)"
}

output "backend_config_snippet" {
  value       = <<-EOT
    # Paste into backend.tf, replace APP01 with your learner prefix, and choose dev, uat, or prod.
    terraform {
      backend "azurerm" {
        resource_group_name  = "${azurerm_resource_group.state.name}"
        storage_account_name = "${azurerm_storage_account.state.name}"
        container_name       = "${azurerm_storage_container.state.name}"
        key                  = "training/APP01/dev/terraform.tfstate"
        use_azuread_auth     = true
      }
    }
  EOT
  description = "Backend configuration template for the learner state contract. Replace APP01 and select dev, uat, or prod."
}

output "backend_hcl_snippet" {
  value       = <<-EOT
    # Save as backend.hcl (gitignored) and use: terraform init -backend-config=backend.hcl
    resource_group_name  = "${azurerm_resource_group.state.name}"
    storage_account_name = "${azurerm_storage_account.state.name}"
    container_name       = "${azurerm_storage_container.state.name}"
    key                  = "training/APP01/dev/terraform.tfstate"
    use_azuread_auth     = true
  EOT
  description = "Partial backend configuration for terraform init -backend-config=backend.hcl"
}

output "key_vault_name" {
  value       = azurerm_key_vault.secrets.name
  description = "Name of the Azure Key Vault storing all secrets"
}

output "key_vault_id" {
  value       = azurerm_key_vault.secrets.id
  description = "Resource ID of the Azure Key Vault"
}

output "key_vault_uri" {
  value       = azurerm_key_vault.secrets.vault_uri
  description = "URI of the Azure Key Vault (for Azure DevOps service connection)"
}

output "key_vault_secret_names" {
  value = {
    snowflake_organization = "SnowflakeOrganization"
    snowflake_account      = "SnowflakeAccount"
    snowflake_user         = "SnowflakeUser"
    snowflake_role         = "SnowflakeRole"
    snowflake_pat          = "SnowflakePAT"
    arm_client_id          = "ArmClientId"
    arm_client_secret      = "ArmClientSecret"
    arm_tenant_id          = "ArmTenantId"
    arm_subscription_id    = "ArmSubscriptionId"
  }
  description = "Map of secret names stored in Key Vault (for Azure DevOps variable group mapping)"
}

output "shared_env_snippet" {
  value       = <<-EOT
    # config/shared.env — committed to Git, no secrets.
    # Generated by 00-bootstrap. Copy this to config/shared.env in the starter repo.
    SNOWFLAKE_ORGANIZATION=${var.snowflake_organization}
    SNOWFLAKE_ACCOUNT=${var.snowflake_account}
    SNOWFLAKE_USER=${var.snowflake_user}
    SNOWFLAKE_ROLE=${var.snowflake_role}
    KEY_VAULT_NAME=${var.key_vault_name}
    ARM_SUBSCRIPTION_ID=${var.arm_subscription_id}
    ARM_TENANT_ID=${var.arm_tenant_id}
    ARM_RESOURCE_GROUP=${var.resource_group_name}
    ARM_STORAGE_ACCOUNT=${var.storage_account_name}
    ARM_CONTAINER=${var.container_name}
    ARM_LOCATION=${var.azure_location}
    ARM_CLIENT_ID=${var.arm_client_id}
  EOT
  description = "Snippet for config/shared.env (committed, no secrets). Paste into the starter repo."
  sensitive   = true
}

output "learner_pat_setup_commands" {
  value = {
    for prefix in var.snowflake_learner_prefixes :
    prefix => "az keyvault secret set --vault-name ${var.key_vault_name} --name SnowflakePAT-${prefix} --value <PAT>"
  }
  description = "Commands for the instructor to set per-learner PATs in Key Vault."
}
