USE DATABASE DB_FINANCE_DEV;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW.LEDGER (
  ENTRY_ID NUMBER NOT NULL,
  ACCOUNT_CODE VARCHAR NOT NULL,
  ENTRY_TS TIMESTAMP_NTZ NOT NULL,
  AMOUNT NUMBER(18, 2) NOT NULL
);

USE SCHEMA SILVER;

CREATE OR REPLACE VIEW SILVER.LEDGER_VALIDATED AS
SELECT ENTRY_ID, ACCOUNT_CODE, ENTRY_TS, AMOUNT
FROM RAW.LEDGER
WHERE ACCOUNT_CODE IS NOT NULL;

USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.DAILY_BALANCE AS
SELECT TO_DATE(ENTRY_TS) AS ENTRY_DATE, SUM(AMOUNT) AS NET_AMOUNT
FROM SILVER.LEDGER_VALIDATED
GROUP BY ENTRY_DATE;
